version:  "3.0"
services:
  
  otel-collector:
    image: otel/opentelemetry-collector:0.145.0
    restart: always 
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
      - victoria-traces
      - victoria-logs
      - victoria-metrics 

  victoria-traces:
    image: victoriametrics/victoria-traces:latest
    restart: always
    ports:
      - 10428:10428/tcp
    volumes:
      - ./victoria-traces-data:/victoria-traces-data

  victoria-logs:
    image: victoriametrics/victoria-logs:latest
    restart: always
    command:
      - "--storageDataPath=/victoria-logs-data"
      - "--httpListenAddr=:9428"
      - "--loggerLevel=INFO"
      - "--retentionPeriod=30d"
    ports:
      - 9428:9428/tcp
    volumes:
      - ./victoria-logs-data:/victoria-logs-data

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.144.0
    ports:
      # HTTP API and OTLP ingestion endpoint
      - "8428:8428"
    volumes:
      - ./victoria-metrics-data:/victoria-metrics-data
    environment:
      storageDataPath: "victoria-metrics-data"
      # Data retention period (how long metrics are kept)
      retentionPeriod: "90d"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.1.0-24320339380
    restart: always
    ports:
      - 3000:3000/tcp
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - otel-collector
    environment:
      GF_INSTALL_PLUGINS: "victoriametrics-metrics-datasource,victoriametrics-logs-datasource"

  lgtm:
    image: grafana/otel-lgtm:0.28.0
    container_name: lgtm
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
      - GF_PATHS_CONFIG=/otel-lgtm/grafana/conf/grafana.ini
      - GF_SERVER_ROOT_URL=http://diplotaxis7-dev.v212.abes.fr:3000/
    volumes:
      - ./lgtm/grafana/data:/data/grafana/data
      - ./lgtm/prometheus/data:/data/prometheus
      - ./lgtm/loki/data:/data/loki
      - ./lgtm/pyroscope/data:/data/pyroscope
      - ./lgtm/tempo/data:/data/tempo
      - ./lgtm/prometheus/prometheus.yml:/otel-lgtm/prometheus.yaml
    ports:
        - "4317:4317"
        - "4318:4318"
        - "3000:3000"
volumes:
  grafanadata: {}

