receivers:
  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # Data sources: traces, metrics, logs
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`
  #debug:
  #  verbosity: detailed
  otlp_http:
    # endpoint: http://victoria-traces:10428/insert/opentelemetry
    traces_endpoint: http://victoria-traces:10428/insert/opentelemetry/v1/traces
    metrics_endpoint : http://victoria-metrics:8428/opentelemetry/v1/metrics
    logs_endpoint : http://victoria-logs:9428/insert/opentelemetry/v1/logs

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch] 
      exporters: [otlp_http]

